### ISSUE TITLE
wrong error message

### ISSUE THREAD

**Issue by wrohdewald** [cosmocode/dokuwiki-plugin-farmer#31]
The Animal directory must outside of the Farm dokuwiki.

Bug:

The Animal directory must be outside of the Farm dokuwiki.

Wish:

The Animal directory must be outside of the Farm /var/lib/farm_dokuwiki
(replace that with actual value)

**Comment by poVoq** [comment]
Same or similar issue here (using "Frusterick Manners").

Also seems like this wasn't really fixed: https://github.com/cosmocode/dokuwiki-plugin-farmer/issues/4

I am trying to set it up on a shared host. My main doku wiki is under /www/wiki/
Putting in "../wikifarm" as suggested by the plug-in results in the above error. Neither does "../wikifarm/" work.
What seems to get me a bit further is "/../wikifarm/"
But similar to putting in "/www/wikifarm/" as an more absolute directory it results in the error: "The Animal directory could not be created. Are the permissions correct?"

Creating the directory manually doesn't make a difference. Changing directory permissions is limited due to this being a shared host, but I guess it should work as under "www" things seem permissible to websites?

**Comment by poVoq** [comment]
Works now, thanks a lot!
